feature: non-finalized orders budget
debridge-finance/dln-taker pull request #84
Opened 2023-04-27 08:44 UTC by mncdg

This PR implements a budget (a hard cap) of all successfully fulfilled orders' value (expressed in USD) that were not reached
yet guaranteed finality at the given point in time.

For example, if you have allowed to fulfill orders worth $1 from this chain after 1 block confirmation:

```ts
      constraints: {
        requiredConfirmationsThresholds: [
           // worth <$100: 1+ block confirmation
           {thresholdAmountInUSD: 100, minBlockConfirmations: 1},
        ],
        // worth >$100: guaranteed block confirmations (12)
     }
```

and there is an accidental flood of 100,000 orders worth $1 occurs, you probably want to prevent this by setting the budget for non-finalized orders. If you set `nonFinalizedTVLBudget` to "100", than only first hundred of one-dollar orders would be attempted to be fulfilled, and all other orders would be postponed to the internal queue where they would be pulled one by one as soon as fulfilled orders are being finalized:

```ts
      constraints: {
        requiredConfirmationsThresholds: [
           // worth <$100: 1+ block confirmation
           {thresholdAmountInUSD: 100, minBlockConfirmations: 1},
        ],
        // worth >$100: guaranteed block confirmations (12)

        // Defines a TVL hard cap for orders coming from this chain that were fulfilled before getting guaranteedly finalized.
        nonFinalizedTVLBudget: 100,
     }
```

Task ID: DEV-2505

2023-05-15 13:16 UTC, alexeychr requested changes
Have breaches in the logic flow.

Add description

2023-05-15 13:16 UTC, alexeychr commented on src/processors/universal.ts
> +        this.unconfirmedOrdersBudgetController.removeOrder(orderId, logger);
additionally, add to the 'Fulfilled' event

2023-05-15 13:16 UTC, alexeychr commented on src/processors/universal.ts
> +
This is nonsense: you literally add confirmed order (isConfirmed==true) to the list of unconfirmed orders. How can this happen? 

Also, why do you perform validation after the order has been fulfilled, why?

2023-05-15 13:16 UTC, alexeychr commented on src/processors/universal.ts
> +      this.unconfirmedOrdersBudgetController.validateOrder(orderId, usdWorth, logger);
Perform validation in the `'Confirmed' in finalizationInfo` section

2023-05-15 13:16 UTC, alexeychr commented on src/processors/UnconfirmedOrdersBudgetController.ts
> +            const message = `Order with usd worth ${usdWorth} is out of budget ${this.unconfirmedOrdersBudgetInUSD}(spent ${this.spentBudgetInUSD})`;
misleading message

2023-05-15 13:17 UTC, alexeychr requested changes
Have breaches in the logic flow.

Add description

2023-06-19 14:59 UTC, merrymari commented
Task linked: [DEV-2505 В dln taker в настройках custom finality сделать потолок суммы долларовых эквивалентов всех не финализированных ордеров](https://app.clickup.com/t/4717986/DEV-2505)

2023-06-20 12:16 UTC, alexeychr approved these changes

2023-06-20 12:16 UTC, merged